
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iibvdqcwycrcyskxvsgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpYnZkcWN3eWNyY3lza3h2c2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzQ4MzEsImV4cCI6MjA1ODAxMDgzMX0.KZfIOLYclaOtn3WX_za7ti3Q0qgz06CtU5wjkV8IasU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);